In [1]:
import numpy as np

### Q1) Create an array of all even integers from 30 to 70:


In [4]:
array= np.arange(30,70,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


### Q2) Generate an array of 15 random numbers from a standard normal distribution:

In [5]:
random_numbers = np.random.randn(15)
print(random_numbers)

[-0.97384012  0.75904275 -0.59763925 -0.23413806 -1.21417045 -0.64543728
  0.07181077  0.59936228 -0.32340301 -0.1084111   2.27550036  0.81715696
  0.02919984  0.34323262  0.01264367]


### Q3) Compute the cross-product of two matrices in NumPy:

In [6]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

cross_product = np.cross(matrix_a, matrix_b)
print(cross_product)

[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


### Q4) Compute the determinant of an array using NumPy:

In [11]:
matrix = np.array([[9, 4], [3, 2]])

determinant = np.linalg.det(matrix)
print(determinant)

6.000000000000003


### Q5) Create a 3x3x3 array with random values using NumPy:

In [12]:
random_3d_array = np.random.random((3, 3, 3))
print(random_3d_array)

[[[0.53670453 0.35114122 0.94352117]
  [0.87000814 0.98344304 0.77795066]
  [0.84573117 0.6264565  0.40656293]]

 [[0.41808257 0.61929621 0.28654561]
  [0.91716395 0.33210846 0.16582889]
  [0.25870939 0.09554998 0.93343286]]

 [[0.03248714 0.04690003 0.1409394 ]
  [0.72290897 0.25007711 0.8601727 ]
  [0.00145491 0.75436318 0.93561044]]]


### Q6) Create a 5x5 array with random values and find the minimum and maximum values using NumPy:

In [13]:
random_5x5_array = np.random.random((5, 5))
min_value = np.min(random_5x5_array)
max_value = np.max(random_5x5_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.05545023313724562
Maximum value: 0.9861844140117939


### Q7) Compute the mean, standard deviation, and variance of a given array along the second axis in NumPy:

In [14]:
given_array = np.array([[1, 2, 3], [4, 5, 6]])

mean_value = np.mean(given_array, axis=1)
std_deviation = np.std(given_array, axis=1)
variance = np.var(given_array, axis=1)

print("Mean along the second axis:", mean_value)
print("Standard Deviation along the second axis:", std_deviation)
print("Variance along the second axis:", variance)

Mean along the second axis: [2. 5.]
Standard Deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
